{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipecd.fullname" . }}
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |-
{{ tpl .Values.config.data . | indent 4 }}
{{- end }}
