args:
  projectID: your-project-id
  pipedID: your-piped-id
  pipedKey: your-piped-key
  controlPlaneAddress: "pipecd:443"
  useFakeAPI: true
  enableDefaultKubernetesCloudProvider: true

service:
  type: ClusterIP
  port: 9085

image: {}

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

config: |
  apiVersion: pipecd.dev/v1beta1
  kind: Piped
  spec:
    syncInterval: 1m
    git:
      sshKeyFile: /etc/piped-secret/sshkey
      accessTokenFile: /etc/piped-secret/gittoken
    repositories:
      - repoId: debug
        remote: git@github.com:pipe-cd/debug.git
        branch: master
      - repoId: debug-not-master
        remote: git@github.com:pipe-cd/debug.git
        branch: not-master
